-- ══════════════════════════════════════════════════════════════════
-- SynerGy Apex LATAM — SQL Corrections  (2026-05-19 03:04 UTC)
-- Generated by audit_all_countries.py  |  Execute in Supabase SQL editor
-- ══════════════════════════════════════════════════════════════════

-- ── PRE-AUDIT SELECT ────────────────────────────────────────────
SELECT country, pib, pib_crecimiento, inflacion, tasa_bc, desempleo,
       poblacion, bancarizacion
FROM countries
ORDER BY country;

-- ── CORRECTIONS (❌ errors only) ─────────────────────────────────

-- Chile
UPDATE countries SET
  pib_crecimiento = 2.5,
  fecha_actualizacion = NOW()
WHERE country = 'Chile';

-- Perú
UPDATE countries SET
  pib_crecimiento = 3.0,
  desempleo = 5.7,
  fecha_actualizacion = NOW()
WHERE country = 'Perú';

-- ── POST-AUDIT VERIFICATION ─────────────────────────────────────
SELECT country, pib, pib_crecimiento, inflacion, tasa_bc, desempleo,
       poblacion, bancarizacion, fecha_actualizacion
FROM countries
ORDER BY country;